/*
Copyright The clickpaas-controller Authors.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "l0calh0st.cn/clickpaas-operator/pkg/apis/middleware/v1alpha1"
	scheme "l0calh0st.cn/clickpaas-operator/pkg/client/clientset/versioned/scheme"
)

// DiamondsGetter has a method to return a DiamondInterface.
// A group's client should implement this interface.
type DiamondsGetter interface {
	Diamonds(namespace string) DiamondInterface
}

// DiamondInterface has methods to work with Diamond resources.
type DiamondInterface interface {
	Create(ctx context.Context, diamond *v1alpha1.Diamond, opts v1.CreateOptions) (*v1alpha1.Diamond, error)
	Update(ctx context.Context, diamond *v1alpha1.Diamond, opts v1.UpdateOptions) (*v1alpha1.Diamond, error)
	UpdateStatus(ctx context.Context, diamond *v1alpha1.Diamond, opts v1.UpdateOptions) (*v1alpha1.Diamond, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Diamond, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.DiamondList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Diamond, err error)
	DiamondExpansion
}

// diamonds implements DiamondInterface
type diamonds struct {
	client rest.Interface
	ns     string
}

// newDiamonds returns a Diamonds
func newDiamonds(c *MiddlewareV1alpha1Client, namespace string) *diamonds {
	return &diamonds{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the diamond, and returns the corresponding diamond object, and an error if there is any.
func (c *diamonds) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Diamond, err error) {
	result = &v1alpha1.Diamond{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("diamonds").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Diamonds that match those selectors.
func (c *diamonds) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DiamondList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.DiamondList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("diamonds").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested diamonds.
func (c *diamonds) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("diamonds").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a diamond and creates it.  Returns the server's representation of the diamond, and an error, if there is any.
func (c *diamonds) Create(ctx context.Context, diamond *v1alpha1.Diamond, opts v1.CreateOptions) (result *v1alpha1.Diamond, err error) {
	result = &v1alpha1.Diamond{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("diamonds").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(diamond).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a diamond and updates it. Returns the server's representation of the diamond, and an error, if there is any.
func (c *diamonds) Update(ctx context.Context, diamond *v1alpha1.Diamond, opts v1.UpdateOptions) (result *v1alpha1.Diamond, err error) {
	result = &v1alpha1.Diamond{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("diamonds").
		Name(diamond.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(diamond).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *diamonds) UpdateStatus(ctx context.Context, diamond *v1alpha1.Diamond, opts v1.UpdateOptions) (result *v1alpha1.Diamond, err error) {
	result = &v1alpha1.Diamond{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("diamonds").
		Name(diamond.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(diamond).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the diamond and deletes it. Returns an error if one occurs.
func (c *diamonds) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("diamonds").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *diamonds) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("diamonds").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched diamond.
func (c *diamonds) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Diamond, err error) {
	result = &v1alpha1.Diamond{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("diamonds").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
