/*
Copyright The clickpaas-controller Authors.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type DiamondExpansion interface{}

type IdGenerateExpansion interface{}

type LtsJobTrackerExpansion interface{}

type MongoClusterExpansion interface{}

type MysqlClusterExpansion interface{}

type RedisGCacheExpansion interface{}

type RocketmqExpansion interface{}

type ZookeeperClusterExpansion interface{}
