/*
Copyright The clickpaas-controller Authors.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "l0calh0st.cn/clickpaas-operator/pkg/apis/middleware/v1alpha1"
	scheme "l0calh0st.cn/clickpaas-operator/pkg/client/clientset/versioned/scheme"
)

// LtsJobTrackersGetter has a method to return a LtsJobTrackerInterface.
// A group's client should implement this interface.
type LtsJobTrackersGetter interface {
	LtsJobTrackers(namespace string) LtsJobTrackerInterface
}

// LtsJobTrackerInterface has methods to work with LtsJobTracker resources.
type LtsJobTrackerInterface interface {
	Create(ctx context.Context, ltsJobTracker *v1alpha1.LtsJobTracker, opts v1.CreateOptions) (*v1alpha1.LtsJobTracker, error)
	Update(ctx context.Context, ltsJobTracker *v1alpha1.LtsJobTracker, opts v1.UpdateOptions) (*v1alpha1.LtsJobTracker, error)
	UpdateStatus(ctx context.Context, ltsJobTracker *v1alpha1.LtsJobTracker, opts v1.UpdateOptions) (*v1alpha1.LtsJobTracker, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.LtsJobTracker, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.LtsJobTrackerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LtsJobTracker, err error)
	LtsJobTrackerExpansion
}

// ltsJobTrackers implements LtsJobTrackerInterface
type ltsJobTrackers struct {
	client rest.Interface
	ns     string
}

// newLtsJobTrackers returns a LtsJobTrackers
func newLtsJobTrackers(c *MiddlewareV1alpha1Client, namespace string) *ltsJobTrackers {
	return &ltsJobTrackers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the ltsJobTracker, and returns the corresponding ltsJobTracker object, and an error if there is any.
func (c *ltsJobTrackers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.LtsJobTracker, err error) {
	result = &v1alpha1.LtsJobTracker{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ltsjobtrackers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of LtsJobTrackers that match those selectors.
func (c *ltsJobTrackers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.LtsJobTrackerList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.LtsJobTrackerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ltsjobtrackers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested ltsJobTrackers.
func (c *ltsJobTrackers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("ltsjobtrackers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a ltsJobTracker and creates it.  Returns the server's representation of the ltsJobTracker, and an error, if there is any.
func (c *ltsJobTrackers) Create(ctx context.Context, ltsJobTracker *v1alpha1.LtsJobTracker, opts v1.CreateOptions) (result *v1alpha1.LtsJobTracker, err error) {
	result = &v1alpha1.LtsJobTracker{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("ltsjobtrackers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(ltsJobTracker).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a ltsJobTracker and updates it. Returns the server's representation of the ltsJobTracker, and an error, if there is any.
func (c *ltsJobTrackers) Update(ctx context.Context, ltsJobTracker *v1alpha1.LtsJobTracker, opts v1.UpdateOptions) (result *v1alpha1.LtsJobTracker, err error) {
	result = &v1alpha1.LtsJobTracker{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("ltsjobtrackers").
		Name(ltsJobTracker.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(ltsJobTracker).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *ltsJobTrackers) UpdateStatus(ctx context.Context, ltsJobTracker *v1alpha1.LtsJobTracker, opts v1.UpdateOptions) (result *v1alpha1.LtsJobTracker, err error) {
	result = &v1alpha1.LtsJobTracker{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("ltsjobtrackers").
		Name(ltsJobTracker.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(ltsJobTracker).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the ltsJobTracker and deletes it. Returns an error if one occurs.
func (c *ltsJobTrackers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ltsjobtrackers").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *ltsJobTrackers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ltsjobtrackers").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched ltsJobTracker.
func (c *ltsJobTrackers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LtsJobTracker, err error) {
	result = &v1alpha1.LtsJobTracker{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("ltsjobtrackers").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
