/*
Copyright The clickpaas-controller Authors.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "l0calh0st.cn/clickpaas-operator/pkg/apis/middleware/v1alpha1"
	scheme "l0calh0st.cn/clickpaas-operator/pkg/client/clientset/versioned/scheme"
)

// MysqlClustersGetter has a method to return a MysqlClusterInterface.
// A group's client should implement this interface.
type MysqlClustersGetter interface {
	MysqlClusters(namespace string) MysqlClusterInterface
}

// MysqlClusterInterface has methods to work with MysqlCluster resources.
type MysqlClusterInterface interface {
	Create(ctx context.Context, mysqlCluster *v1alpha1.MysqlCluster, opts v1.CreateOptions) (*v1alpha1.MysqlCluster, error)
	Update(ctx context.Context, mysqlCluster *v1alpha1.MysqlCluster, opts v1.UpdateOptions) (*v1alpha1.MysqlCluster, error)
	UpdateStatus(ctx context.Context, mysqlCluster *v1alpha1.MysqlCluster, opts v1.UpdateOptions) (*v1alpha1.MysqlCluster, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.MysqlCluster, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.MysqlClusterList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MysqlCluster, err error)
	MysqlClusterExpansion
}

// mysqlClusters implements MysqlClusterInterface
type mysqlClusters struct {
	client rest.Interface
	ns     string
}

// newMysqlClusters returns a MysqlClusters
func newMysqlClusters(c *MiddlewareV1alpha1Client, namespace string) *mysqlClusters {
	return &mysqlClusters{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the mysqlCluster, and returns the corresponding mysqlCluster object, and an error if there is any.
func (c *mysqlClusters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MysqlCluster, err error) {
	result = &v1alpha1.MysqlCluster{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("mysqlclusters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MysqlClusters that match those selectors.
func (c *mysqlClusters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MysqlClusterList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.MysqlClusterList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("mysqlclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested mysqlClusters.
func (c *mysqlClusters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("mysqlclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a mysqlCluster and creates it.  Returns the server's representation of the mysqlCluster, and an error, if there is any.
func (c *mysqlClusters) Create(ctx context.Context, mysqlCluster *v1alpha1.MysqlCluster, opts v1.CreateOptions) (result *v1alpha1.MysqlCluster, err error) {
	result = &v1alpha1.MysqlCluster{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("mysqlclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(mysqlCluster).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a mysqlCluster and updates it. Returns the server's representation of the mysqlCluster, and an error, if there is any.
func (c *mysqlClusters) Update(ctx context.Context, mysqlCluster *v1alpha1.MysqlCluster, opts v1.UpdateOptions) (result *v1alpha1.MysqlCluster, err error) {
	result = &v1alpha1.MysqlCluster{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("mysqlclusters").
		Name(mysqlCluster.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(mysqlCluster).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *mysqlClusters) UpdateStatus(ctx context.Context, mysqlCluster *v1alpha1.MysqlCluster, opts v1.UpdateOptions) (result *v1alpha1.MysqlCluster, err error) {
	result = &v1alpha1.MysqlCluster{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("mysqlclusters").
		Name(mysqlCluster.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(mysqlCluster).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the mysqlCluster and deletes it. Returns an error if one occurs.
func (c *mysqlClusters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("mysqlclusters").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *mysqlClusters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("mysqlclusters").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched mysqlCluster.
func (c *mysqlClusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MysqlCluster, err error) {
	result = &v1alpha1.MysqlCluster{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("mysqlclusters").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
