/*
Copyright The clickpaas-controller Authors.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "l0calh0st.cn/clickpaas-operator/pkg/apis/middleware/v1alpha1"
	scheme "l0calh0st.cn/clickpaas-operator/pkg/client/clientset/versioned/scheme"
)

// RocketmqsGetter has a method to return a RocketmqInterface.
// A group's client should implement this interface.
type RocketmqsGetter interface {
	Rocketmqs(namespace string) RocketmqInterface
}

// RocketmqInterface has methods to work with Rocketmq resources.
type RocketmqInterface interface {
	Create(ctx context.Context, rocketmq *v1alpha1.Rocketmq, opts v1.CreateOptions) (*v1alpha1.Rocketmq, error)
	Update(ctx context.Context, rocketmq *v1alpha1.Rocketmq, opts v1.UpdateOptions) (*v1alpha1.Rocketmq, error)
	UpdateStatus(ctx context.Context, rocketmq *v1alpha1.Rocketmq, opts v1.UpdateOptions) (*v1alpha1.Rocketmq, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Rocketmq, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.RocketmqList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Rocketmq, err error)
	RocketmqExpansion
}

// rocketmqs implements RocketmqInterface
type rocketmqs struct {
	client rest.Interface
	ns     string
}

// newRocketmqs returns a Rocketmqs
func newRocketmqs(c *MiddlewareV1alpha1Client, namespace string) *rocketmqs {
	return &rocketmqs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the rocketmq, and returns the corresponding rocketmq object, and an error if there is any.
func (c *rocketmqs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Rocketmq, err error) {
	result = &v1alpha1.Rocketmq{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("rocketmqs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Rocketmqs that match those selectors.
func (c *rocketmqs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RocketmqList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.RocketmqList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("rocketmqs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested rocketmqs.
func (c *rocketmqs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("rocketmqs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a rocketmq and creates it.  Returns the server's representation of the rocketmq, and an error, if there is any.
func (c *rocketmqs) Create(ctx context.Context, rocketmq *v1alpha1.Rocketmq, opts v1.CreateOptions) (result *v1alpha1.Rocketmq, err error) {
	result = &v1alpha1.Rocketmq{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("rocketmqs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(rocketmq).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a rocketmq and updates it. Returns the server's representation of the rocketmq, and an error, if there is any.
func (c *rocketmqs) Update(ctx context.Context, rocketmq *v1alpha1.Rocketmq, opts v1.UpdateOptions) (result *v1alpha1.Rocketmq, err error) {
	result = &v1alpha1.Rocketmq{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("rocketmqs").
		Name(rocketmq.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(rocketmq).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *rocketmqs) UpdateStatus(ctx context.Context, rocketmq *v1alpha1.Rocketmq, opts v1.UpdateOptions) (result *v1alpha1.Rocketmq, err error) {
	result = &v1alpha1.Rocketmq{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("rocketmqs").
		Name(rocketmq.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(rocketmq).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the rocketmq and deletes it. Returns an error if one occurs.
func (c *rocketmqs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("rocketmqs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *rocketmqs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("rocketmqs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched rocketmq.
func (c *rocketmqs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Rocketmq, err error) {
	result = &v1alpha1.Rocketmq{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("rocketmqs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
