/*
Copyright The clickpaas-controller Authors.
*/

// Code generated by informer-gen. DO NOT EDIT.

package externalversions

import (
	"fmt"

	schema "k8s.io/apimachinery/pkg/runtime/schema"
	cache "k8s.io/client-go/tools/cache"
	v1alpha1 "l0calh0st.cn/clickpaas-operator/pkg/apis/middleware/v1alpha1"
)

// GenericInformer is type of SharedIndexInformer which will locate and delegate to other
// sharedInformers based on type
type GenericInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() cache.GenericLister
}

type genericInformer struct {
	informer cache.SharedIndexInformer
	resource schema.GroupResource
}

// Informer returns the SharedIndexInformer.
func (f *genericInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

// Lister returns the GenericLister.
func (f *genericInformer) Lister() cache.GenericLister {
	return cache.NewGenericLister(f.Informer().GetIndexer(), f.resource)
}

// ForResource gives generic access to a shared informer of the matching type
// TODO extend this to unknown resources with a client pool
func (f *sharedInformerFactory) ForResource(resource schema.GroupVersionResource) (GenericInformer, error) {
	switch resource {
	// Group=middleware.l0calh0st.cn, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithResource("diamonds"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Middleware().V1alpha1().Diamonds().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("idgenerates"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Middleware().V1alpha1().IdGenerates().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("ltsjobtrackers"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Middleware().V1alpha1().LtsJobTrackers().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("mongoclusters"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Middleware().V1alpha1().MongoClusters().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("mysqlclusters"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Middleware().V1alpha1().MysqlClusters().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("redisgcaches"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Middleware().V1alpha1().RedisGCaches().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("rocketmqs"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Middleware().V1alpha1().Rocketmqs().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("zookeeperclusters"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Middleware().V1alpha1().ZookeeperClusters().Informer()}, nil

	}

	return nil, fmt.Errorf("no informer found for %v", resource)
}
