/*
Copyright The clickpaas-controller Authors.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "l0calh0st.cn/clickpaas-operator/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Diamonds returns a DiamondInformer.
	Diamonds() DiamondInformer
	// IdGenerates returns a IdGenerateInformer.
	IdGenerates() IdGenerateInformer
	// LtsJobTrackers returns a LtsJobTrackerInformer.
	LtsJobTrackers() LtsJobTrackerInformer
	// MongoClusters returns a MongoClusterInformer.
	MongoClusters() MongoClusterInformer
	// MysqlClusters returns a MysqlClusterInformer.
	MysqlClusters() MysqlClusterInformer
	// RedisGCaches returns a RedisGCacheInformer.
	RedisGCaches() RedisGCacheInformer
	// Rocketmqs returns a RocketmqInformer.
	Rocketmqs() RocketmqInformer
	// ZookeeperClusters returns a ZookeeperClusterInformer.
	ZookeeperClusters() ZookeeperClusterInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Diamonds returns a DiamondInformer.
func (v *version) Diamonds() DiamondInformer {
	return &diamondInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// IdGenerates returns a IdGenerateInformer.
func (v *version) IdGenerates() IdGenerateInformer {
	return &idGenerateInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// LtsJobTrackers returns a LtsJobTrackerInformer.
func (v *version) LtsJobTrackers() LtsJobTrackerInformer {
	return &ltsJobTrackerInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// MongoClusters returns a MongoClusterInformer.
func (v *version) MongoClusters() MongoClusterInformer {
	return &mongoClusterInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// MysqlClusters returns a MysqlClusterInformer.
func (v *version) MysqlClusters() MysqlClusterInformer {
	return &mysqlClusterInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// RedisGCaches returns a RedisGCacheInformer.
func (v *version) RedisGCaches() RedisGCacheInformer {
	return &redisGCacheInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Rocketmqs returns a RocketmqInformer.
func (v *version) Rocketmqs() RocketmqInformer {
	return &rocketmqInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ZookeeperClusters returns a ZookeeperClusterInformer.
func (v *version) ZookeeperClusters() ZookeeperClusterInformer {
	return &zookeeperClusterInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
