/*
Copyright The clickpaas-controller Authors.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "l0calh0st.cn/clickpaas-operator/pkg/apis/middleware/v1alpha1"
)

// FakeRedisGCaches implements RedisGCacheInterface
type FakeRedisGCaches struct {
	Fake *FakeMiddlewareV1alpha1
	ns   string
}

var redisgcachesResource = schema.GroupVersionResource{Group: "middleware.l0calh0st.cn", Version: "v1alpha1", Resource: "redisgcaches"}

var redisgcachesKind = schema.GroupVersionKind{Group: "middleware.l0calh0st.cn", Version: "v1alpha1", Kind: "RedisGCache"}

// Get takes name of the redisGCache, and returns the corresponding redisGCache object, and an error if there is any.
func (c *FakeRedisGCaches) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.RedisGCache, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(redisgcachesResource, c.ns, name), &v1alpha1.RedisGCache{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RedisGCache), err
}

// List takes label and field selectors, and returns the list of RedisGCaches that match those selectors.
func (c *FakeRedisGCaches) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RedisGCacheList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(redisgcachesResource, redisgcachesKind, c.ns, opts), &v1alpha1.RedisGCacheList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RedisGCacheList{ListMeta: obj.(*v1alpha1.RedisGCacheList).ListMeta}
	for _, item := range obj.(*v1alpha1.RedisGCacheList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested redisGCaches.
func (c *FakeRedisGCaches) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(redisgcachesResource, c.ns, opts))

}

// Create takes the representation of a redisGCache and creates it.  Returns the server's representation of the redisGCache, and an error, if there is any.
func (c *FakeRedisGCaches) Create(ctx context.Context, redisGCache *v1alpha1.RedisGCache, opts v1.CreateOptions) (result *v1alpha1.RedisGCache, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(redisgcachesResource, c.ns, redisGCache), &v1alpha1.RedisGCache{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RedisGCache), err
}

// Update takes the representation of a redisGCache and updates it. Returns the server's representation of the redisGCache, and an error, if there is any.
func (c *FakeRedisGCaches) Update(ctx context.Context, redisGCache *v1alpha1.RedisGCache, opts v1.UpdateOptions) (result *v1alpha1.RedisGCache, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(redisgcachesResource, c.ns, redisGCache), &v1alpha1.RedisGCache{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RedisGCache), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRedisGCaches) UpdateStatus(ctx context.Context, redisGCache *v1alpha1.RedisGCache, opts v1.UpdateOptions) (*v1alpha1.RedisGCache, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(redisgcachesResource, "status", c.ns, redisGCache), &v1alpha1.RedisGCache{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RedisGCache), err
}

// Delete takes name of the redisGCache and deletes it. Returns an error if one occurs.
func (c *FakeRedisGCaches) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(redisgcachesResource, c.ns, name), &v1alpha1.RedisGCache{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRedisGCaches) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(redisgcachesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.RedisGCacheList{})
	return err
}

// Patch applies the patch and returns the patched redisGCache.
func (c *FakeRedisGCaches) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RedisGCache, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(redisgcachesResource, c.ns, name, pt, data, subresources...), &v1alpha1.RedisGCache{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RedisGCache), err
}
