/*
Copyright The clickpaas-controller Authors.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "l0calh0st.cn/clickpaas-operator/pkg/apis/middleware/v1alpha1"
)

// FakeDiamonds implements DiamondInterface
type FakeDiamonds struct {
	Fake *FakeMiddlewareV1alpha1
	ns   string
}

var diamondsResource = schema.GroupVersionResource{Group: "middleware.clickpaas.cn", Version: "v1alpha1", Resource: "diamonds"}

var diamondsKind = schema.GroupVersionKind{Group: "middleware.clickpaas.cn", Version: "v1alpha1", Kind: "Diamond"}

// Get takes name of the diamond, and returns the corresponding diamond object, and an error if there is any.
func (c *FakeDiamonds) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Diamond, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(diamondsResource, c.ns, name), &v1alpha1.Diamond{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Diamond), err
}

// List takes label and field selectors, and returns the list of Diamonds that match those selectors.
func (c *FakeDiamonds) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DiamondList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(diamondsResource, diamondsKind, c.ns, opts), &v1alpha1.DiamondList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DiamondList{ListMeta: obj.(*v1alpha1.DiamondList).ListMeta}
	for _, item := range obj.(*v1alpha1.DiamondList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested diamonds.
func (c *FakeDiamonds) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(diamondsResource, c.ns, opts))

}

// Create takes the representation of a diamond and creates it.  Returns the server's representation of the diamond, and an error, if there is any.
func (c *FakeDiamonds) Create(ctx context.Context, diamond *v1alpha1.Diamond, opts v1.CreateOptions) (result *v1alpha1.Diamond, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(diamondsResource, c.ns, diamond), &v1alpha1.Diamond{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Diamond), err
}

// Update takes the representation of a diamond and updates it. Returns the server's representation of the diamond, and an error, if there is any.
func (c *FakeDiamonds) Update(ctx context.Context, diamond *v1alpha1.Diamond, opts v1.UpdateOptions) (result *v1alpha1.Diamond, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(diamondsResource, c.ns, diamond), &v1alpha1.Diamond{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Diamond), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDiamonds) UpdateStatus(ctx context.Context, diamond *v1alpha1.Diamond, opts v1.UpdateOptions) (*v1alpha1.Diamond, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(diamondsResource, "status", c.ns, diamond), &v1alpha1.Diamond{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Diamond), err
}

// Delete takes name of the diamond and deletes it. Returns an error if one occurs.
func (c *FakeDiamonds) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(diamondsResource, c.ns, name), &v1alpha1.Diamond{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDiamonds) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(diamondsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DiamondList{})
	return err
}

// Patch applies the patch and returns the patched diamond.
func (c *FakeDiamonds) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Diamond, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(diamondsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Diamond{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Diamond), err
}
