/*
Copyright The clickpaas-controller Authors.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "l0calh0st.cn/clickpaas-operator/pkg/apis/middleware/v1alpha1"
)

// FakeIdGenerates implements IdGenerateInterface
type FakeIdGenerates struct {
	Fake *FakeMiddlewareV1alpha1
	ns   string
}

var idgeneratesResource = schema.GroupVersionResource{Group: "middleware.l0calh0st.cn", Version: "v1alpha1", Resource: "idgenerates"}

var idgeneratesKind = schema.GroupVersionKind{Group: "middleware.l0calh0st.cn", Version: "v1alpha1", Kind: "IdGenerate"}

// Get takes name of the idGenerate, and returns the corresponding idGenerate object, and an error if there is any.
func (c *FakeIdGenerates) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IdGenerate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(idgeneratesResource, c.ns, name), &v1alpha1.IdGenerate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IdGenerate), err
}

// List takes label and field selectors, and returns the list of IdGenerates that match those selectors.
func (c *FakeIdGenerates) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IdGenerateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(idgeneratesResource, idgeneratesKind, c.ns, opts), &v1alpha1.IdGenerateList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.IdGenerateList{ListMeta: obj.(*v1alpha1.IdGenerateList).ListMeta}
	for _, item := range obj.(*v1alpha1.IdGenerateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested idGenerates.
func (c *FakeIdGenerates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(idgeneratesResource, c.ns, opts))

}

// Create takes the representation of a idGenerate and creates it.  Returns the server's representation of the idGenerate, and an error, if there is any.
func (c *FakeIdGenerates) Create(ctx context.Context, idGenerate *v1alpha1.IdGenerate, opts v1.CreateOptions) (result *v1alpha1.IdGenerate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(idgeneratesResource, c.ns, idGenerate), &v1alpha1.IdGenerate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IdGenerate), err
}

// Update takes the representation of a idGenerate and updates it. Returns the server's representation of the idGenerate, and an error, if there is any.
func (c *FakeIdGenerates) Update(ctx context.Context, idGenerate *v1alpha1.IdGenerate, opts v1.UpdateOptions) (result *v1alpha1.IdGenerate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(idgeneratesResource, c.ns, idGenerate), &v1alpha1.IdGenerate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IdGenerate), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeIdGenerates) UpdateStatus(ctx context.Context, idGenerate *v1alpha1.IdGenerate, opts v1.UpdateOptions) (*v1alpha1.IdGenerate, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(idgeneratesResource, "status", c.ns, idGenerate), &v1alpha1.IdGenerate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IdGenerate), err
}

// Delete takes name of the idGenerate and deletes it. Returns an error if one occurs.
func (c *FakeIdGenerates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(idgeneratesResource, c.ns, name), &v1alpha1.IdGenerate{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIdGenerates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(idgeneratesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.IdGenerateList{})
	return err
}

// Patch applies the patch and returns the patched idGenerate.
func (c *FakeIdGenerates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IdGenerate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(idgeneratesResource, c.ns, name, pt, data, subresources...), &v1alpha1.IdGenerate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IdGenerate), err
}
