/*
Copyright The clickpaas-controller Authors.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
	v1alpha1 "l0calh0st.cn/clickpaas-operator/pkg/client/clientset/versioned/typed/middleware/v1alpha1"
)

type FakeMiddlewareV1alpha1 struct {
	*testing.Fake
}

func (c *FakeMiddlewareV1alpha1) Diamonds(namespace string) v1alpha1.DiamondInterface {
	return &FakeDiamonds{c, namespace}
}

func (c *FakeMiddlewareV1alpha1) IdGenerates(namespace string) v1alpha1.IdGenerateInterface {
	return &FakeIdGenerates{c, namespace}
}

func (c *FakeMiddlewareV1alpha1) LtsJobTrackers(namespace string) v1alpha1.LtsJobTrackerInterface {
	return &FakeLtsJobTrackers{c, namespace}
}

func (c *FakeMiddlewareV1alpha1) MongoClusters(namespace string) v1alpha1.MongoClusterInterface {
	return &FakeMongoClusters{c, namespace}
}

func (c *FakeMiddlewareV1alpha1) MysqlClusters(namespace string) v1alpha1.MysqlClusterInterface {
	return &FakeMysqlClusters{c, namespace}
}

func (c *FakeMiddlewareV1alpha1) RedisGCaches(namespace string) v1alpha1.RedisGCacheInterface {
	return &FakeRedisGCaches{c, namespace}
}

func (c *FakeMiddlewareV1alpha1) Rocketmqs(namespace string) v1alpha1.RocketmqInterface {
	return &FakeRocketmqs{c, namespace}
}

func (c *FakeMiddlewareV1alpha1) ZookeeperClusters(namespace string) v1alpha1.ZookeeperClusterInterface {
	return &FakeZookeeperClusters{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeMiddlewareV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
