/*
Copyright The clickpaas-controller Authors.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "l0calh0st.cn/clickpaas-operator/pkg/apis/middleware/v1alpha1"
)

// FakeLtsJobTrackers implements LtsJobTrackerInterface
type FakeLtsJobTrackers struct {
	Fake *FakeMiddlewareV1alpha1
	ns   string
}

var ltsjobtrackersResource = schema.GroupVersionResource{Group: "middleware.l0calh0st.cn", Version: "v1alpha1", Resource: "ltsjobtrackers"}

var ltsjobtrackersKind = schema.GroupVersionKind{Group: "middleware.l0calh0st.cn", Version: "v1alpha1", Kind: "LtsJobTracker"}

// Get takes name of the ltsJobTracker, and returns the corresponding ltsJobTracker object, and an error if there is any.
func (c *FakeLtsJobTrackers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.LtsJobTracker, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(ltsjobtrackersResource, c.ns, name), &v1alpha1.LtsJobTracker{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LtsJobTracker), err
}

// List takes label and field selectors, and returns the list of LtsJobTrackers that match those selectors.
func (c *FakeLtsJobTrackers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.LtsJobTrackerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(ltsjobtrackersResource, ltsjobtrackersKind, c.ns, opts), &v1alpha1.LtsJobTrackerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.LtsJobTrackerList{ListMeta: obj.(*v1alpha1.LtsJobTrackerList).ListMeta}
	for _, item := range obj.(*v1alpha1.LtsJobTrackerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested ltsJobTrackers.
func (c *FakeLtsJobTrackers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(ltsjobtrackersResource, c.ns, opts))

}

// Create takes the representation of a ltsJobTracker and creates it.  Returns the server's representation of the ltsJobTracker, and an error, if there is any.
func (c *FakeLtsJobTrackers) Create(ctx context.Context, ltsJobTracker *v1alpha1.LtsJobTracker, opts v1.CreateOptions) (result *v1alpha1.LtsJobTracker, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(ltsjobtrackersResource, c.ns, ltsJobTracker), &v1alpha1.LtsJobTracker{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LtsJobTracker), err
}

// Update takes the representation of a ltsJobTracker and updates it. Returns the server's representation of the ltsJobTracker, and an error, if there is any.
func (c *FakeLtsJobTrackers) Update(ctx context.Context, ltsJobTracker *v1alpha1.LtsJobTracker, opts v1.UpdateOptions) (result *v1alpha1.LtsJobTracker, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(ltsjobtrackersResource, c.ns, ltsJobTracker), &v1alpha1.LtsJobTracker{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LtsJobTracker), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeLtsJobTrackers) UpdateStatus(ctx context.Context, ltsJobTracker *v1alpha1.LtsJobTracker, opts v1.UpdateOptions) (*v1alpha1.LtsJobTracker, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(ltsjobtrackersResource, "status", c.ns, ltsJobTracker), &v1alpha1.LtsJobTracker{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LtsJobTracker), err
}

// Delete takes name of the ltsJobTracker and deletes it. Returns an error if one occurs.
func (c *FakeLtsJobTrackers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(ltsjobtrackersResource, c.ns, name), &v1alpha1.LtsJobTracker{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLtsJobTrackers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(ltsjobtrackersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.LtsJobTrackerList{})
	return err
}

// Patch applies the patch and returns the patched ltsJobTracker.
func (c *FakeLtsJobTrackers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LtsJobTracker, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ltsjobtrackersResource, c.ns, name, pt, data, subresources...), &v1alpha1.LtsJobTracker{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LtsJobTracker), err
}
