/*
Copyright The clickpaas-controller Authors.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "l0calh0st.cn/clickpaas-operator/pkg/apis/middleware/v1alpha1"
)

// FakeZookeeperClusters implements ZookeeperClusterInterface
type FakeZookeeperClusters struct {
	Fake *FakeMiddlewareV1alpha1
	ns   string
}

var zookeeperclustersResource = schema.GroupVersionResource{Group: "middleware.l0calh0st.cn", Version: "v1alpha1", Resource: "zookeeperclusters"}

var zookeeperclustersKind = schema.GroupVersionKind{Group: "middleware.l0calh0st.cn", Version: "v1alpha1", Kind: "ZookeeperCluster"}

// Get takes name of the zookeeperCluster, and returns the corresponding zookeeperCluster object, and an error if there is any.
func (c *FakeZookeeperClusters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ZookeeperCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(zookeeperclustersResource, c.ns, name), &v1alpha1.ZookeeperCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ZookeeperCluster), err
}

// List takes label and field selectors, and returns the list of ZookeeperClusters that match those selectors.
func (c *FakeZookeeperClusters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ZookeeperClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(zookeeperclustersResource, zookeeperclustersKind, c.ns, opts), &v1alpha1.ZookeeperClusterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ZookeeperClusterList{ListMeta: obj.(*v1alpha1.ZookeeperClusterList).ListMeta}
	for _, item := range obj.(*v1alpha1.ZookeeperClusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested zookeeperClusters.
func (c *FakeZookeeperClusters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(zookeeperclustersResource, c.ns, opts))

}

// Create takes the representation of a zookeeperCluster and creates it.  Returns the server's representation of the zookeeperCluster, and an error, if there is any.
func (c *FakeZookeeperClusters) Create(ctx context.Context, zookeeperCluster *v1alpha1.ZookeeperCluster, opts v1.CreateOptions) (result *v1alpha1.ZookeeperCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(zookeeperclustersResource, c.ns, zookeeperCluster), &v1alpha1.ZookeeperCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ZookeeperCluster), err
}

// Update takes the representation of a zookeeperCluster and updates it. Returns the server's representation of the zookeeperCluster, and an error, if there is any.
func (c *FakeZookeeperClusters) Update(ctx context.Context, zookeeperCluster *v1alpha1.ZookeeperCluster, opts v1.UpdateOptions) (result *v1alpha1.ZookeeperCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(zookeeperclustersResource, c.ns, zookeeperCluster), &v1alpha1.ZookeeperCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ZookeeperCluster), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeZookeeperClusters) UpdateStatus(ctx context.Context, zookeeperCluster *v1alpha1.ZookeeperCluster, opts v1.UpdateOptions) (*v1alpha1.ZookeeperCluster, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(zookeeperclustersResource, "status", c.ns, zookeeperCluster), &v1alpha1.ZookeeperCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ZookeeperCluster), err
}

// Delete takes name of the zookeeperCluster and deletes it. Returns an error if one occurs.
func (c *FakeZookeeperClusters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(zookeeperclustersResource, c.ns, name), &v1alpha1.ZookeeperCluster{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeZookeeperClusters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(zookeeperclustersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ZookeeperClusterList{})
	return err
}

// Patch applies the patch and returns the patched zookeeperCluster.
func (c *FakeZookeeperClusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ZookeeperCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(zookeeperclustersResource, c.ns, name, pt, data, subresources...), &v1alpha1.ZookeeperCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ZookeeperCluster), err
}
