/*
Copyright The clickpaas-controller Authors.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// DiamondListerExpansion allows custom methods to be added to
// DiamondLister.
type DiamondListerExpansion interface{}

// DiamondNamespaceListerExpansion allows custom methods to be added to
// DiamondNamespaceLister.
type DiamondNamespaceListerExpansion interface{}

// IdGenerateListerExpansion allows custom methods to be added to
// IdGenerateLister.
type IdGenerateListerExpansion interface{}

// IdGenerateNamespaceListerExpansion allows custom methods to be added to
// IdGenerateNamespaceLister.
type IdGenerateNamespaceListerExpansion interface{}

// LtsJobTrackerListerExpansion allows custom methods to be added to
// LtsJobTrackerLister.
type LtsJobTrackerListerExpansion interface{}

// LtsJobTrackerNamespaceListerExpansion allows custom methods to be added to
// LtsJobTrackerNamespaceLister.
type LtsJobTrackerNamespaceListerExpansion interface{}

// MongoClusterListerExpansion allows custom methods to be added to
// MongoClusterLister.
type MongoClusterListerExpansion interface{}

// MongoClusterNamespaceListerExpansion allows custom methods to be added to
// MongoClusterNamespaceLister.
type MongoClusterNamespaceListerExpansion interface{}

// MysqlClusterListerExpansion allows custom methods to be added to
// MysqlClusterLister.
type MysqlClusterListerExpansion interface{}

// MysqlClusterNamespaceListerExpansion allows custom methods to be added to
// MysqlClusterNamespaceLister.
type MysqlClusterNamespaceListerExpansion interface{}

// RedisGCacheListerExpansion allows custom methods to be added to
// RedisGCacheLister.
type RedisGCacheListerExpansion interface{}

// RedisGCacheNamespaceListerExpansion allows custom methods to be added to
// RedisGCacheNamespaceLister.
type RedisGCacheNamespaceListerExpansion interface{}

// RocketmqListerExpansion allows custom methods to be added to
// RocketmqLister.
type RocketmqListerExpansion interface{}

// RocketmqNamespaceListerExpansion allows custom methods to be added to
// RocketmqNamespaceLister.
type RocketmqNamespaceListerExpansion interface{}

// ZookeeperClusterListerExpansion allows custom methods to be added to
// ZookeeperClusterLister.
type ZookeeperClusterListerExpansion interface{}

// ZookeeperClusterNamespaceListerExpansion allows custom methods to be added to
// ZookeeperClusterNamespaceLister.
type ZookeeperClusterNamespaceListerExpansion interface{}
