/*
Copyright The clickpaas-controller Authors.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	v1alpha1 "l0calh0st.cn/clickpaas-operator/pkg/apis/middleware/v1alpha1"
)

// IdGenerateLister helps list IdGenerates.
// All objects returned here must be treated as read-only.
type IdGenerateLister interface {
	// List lists all IdGenerates in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.IdGenerate, err error)
	// IdGenerates returns an object that can list and get IdGenerates.
	IdGenerates(namespace string) IdGenerateNamespaceLister
	IdGenerateListerExpansion
}

// idGenerateLister implements the IdGenerateLister interface.
type idGenerateLister struct {
	indexer cache.Indexer
}

// NewIdGenerateLister returns a new IdGenerateLister.
func NewIdGenerateLister(indexer cache.Indexer) IdGenerateLister {
	return &idGenerateLister{indexer: indexer}
}

// List lists all IdGenerates in the indexer.
func (s *idGenerateLister) List(selector labels.Selector) (ret []*v1alpha1.IdGenerate, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.IdGenerate))
	})
	return ret, err
}

// IdGenerates returns an object that can list and get IdGenerates.
func (s *idGenerateLister) IdGenerates(namespace string) IdGenerateNamespaceLister {
	return idGenerateNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// IdGenerateNamespaceLister helps list and get IdGenerates.
// All objects returned here must be treated as read-only.
type IdGenerateNamespaceLister interface {
	// List lists all IdGenerates in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.IdGenerate, err error)
	// Get retrieves the IdGenerate from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.IdGenerate, error)
	IdGenerateNamespaceListerExpansion
}

// idGenerateNamespaceLister implements the IdGenerateNamespaceLister
// interface.
type idGenerateNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all IdGenerates in the indexer for a given namespace.
func (s idGenerateNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.IdGenerate, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.IdGenerate))
	})
	return ret, err
}

// Get retrieves the IdGenerate from the indexer for a given namespace and name.
func (s idGenerateNamespaceLister) Get(name string) (*v1alpha1.IdGenerate, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("idgenerate"), name)
	}
	return obj.(*v1alpha1.IdGenerate), nil
}
