/*
Copyright The clickpaas-controller Authors.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	v1alpha1 "l0calh0st.cn/clickpaas-operator/pkg/apis/middleware/v1alpha1"
)

// LtsJobTrackerLister helps list LtsJobTrackers.
// All objects returned here must be treated as read-only.
type LtsJobTrackerLister interface {
	// List lists all LtsJobTrackers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.LtsJobTracker, err error)
	// LtsJobTrackers returns an object that can list and get LtsJobTrackers.
	LtsJobTrackers(namespace string) LtsJobTrackerNamespaceLister
	LtsJobTrackerListerExpansion
}

// ltsJobTrackerLister implements the LtsJobTrackerLister interface.
type ltsJobTrackerLister struct {
	indexer cache.Indexer
}

// NewLtsJobTrackerLister returns a new LtsJobTrackerLister.
func NewLtsJobTrackerLister(indexer cache.Indexer) LtsJobTrackerLister {
	return &ltsJobTrackerLister{indexer: indexer}
}

// List lists all LtsJobTrackers in the indexer.
func (s *ltsJobTrackerLister) List(selector labels.Selector) (ret []*v1alpha1.LtsJobTracker, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.LtsJobTracker))
	})
	return ret, err
}

// LtsJobTrackers returns an object that can list and get LtsJobTrackers.
func (s *ltsJobTrackerLister) LtsJobTrackers(namespace string) LtsJobTrackerNamespaceLister {
	return ltsJobTrackerNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// LtsJobTrackerNamespaceLister helps list and get LtsJobTrackers.
// All objects returned here must be treated as read-only.
type LtsJobTrackerNamespaceLister interface {
	// List lists all LtsJobTrackers in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.LtsJobTracker, err error)
	// Get retrieves the LtsJobTracker from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.LtsJobTracker, error)
	LtsJobTrackerNamespaceListerExpansion
}

// ltsJobTrackerNamespaceLister implements the LtsJobTrackerNamespaceLister
// interface.
type ltsJobTrackerNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all LtsJobTrackers in the indexer for a given namespace.
func (s ltsJobTrackerNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.LtsJobTracker, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.LtsJobTracker))
	})
	return ret, err
}

// Get retrieves the LtsJobTracker from the indexer for a given namespace and name.
func (s ltsJobTrackerNamespaceLister) Get(name string) (*v1alpha1.LtsJobTracker, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("ltsjobtracker"), name)
	}
	return obj.(*v1alpha1.LtsJobTracker), nil
}
