/*
Copyright The clickpaas-controller Authors.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	v1alpha1 "l0calh0st.cn/clickpaas-operator/pkg/apis/middleware/v1alpha1"
)

// RedisGCacheLister helps list RedisGCaches.
// All objects returned here must be treated as read-only.
type RedisGCacheLister interface {
	// List lists all RedisGCaches in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.RedisGCache, err error)
	// RedisGCaches returns an object that can list and get RedisGCaches.
	RedisGCaches(namespace string) RedisGCacheNamespaceLister
	RedisGCacheListerExpansion
}

// redisGCacheLister implements the RedisGCacheLister interface.
type redisGCacheLister struct {
	indexer cache.Indexer
}

// NewRedisGCacheLister returns a new RedisGCacheLister.
func NewRedisGCacheLister(indexer cache.Indexer) RedisGCacheLister {
	return &redisGCacheLister{indexer: indexer}
}

// List lists all RedisGCaches in the indexer.
func (s *redisGCacheLister) List(selector labels.Selector) (ret []*v1alpha1.RedisGCache, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.RedisGCache))
	})
	return ret, err
}

// RedisGCaches returns an object that can list and get RedisGCaches.
func (s *redisGCacheLister) RedisGCaches(namespace string) RedisGCacheNamespaceLister {
	return redisGCacheNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// RedisGCacheNamespaceLister helps list and get RedisGCaches.
// All objects returned here must be treated as read-only.
type RedisGCacheNamespaceLister interface {
	// List lists all RedisGCaches in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.RedisGCache, err error)
	// Get retrieves the RedisGCache from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.RedisGCache, error)
	RedisGCacheNamespaceListerExpansion
}

// redisGCacheNamespaceLister implements the RedisGCacheNamespaceLister
// interface.
type redisGCacheNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all RedisGCaches in the indexer for a given namespace.
func (s redisGCacheNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.RedisGCache, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.RedisGCache))
	})
	return ret, err
}

// Get retrieves the RedisGCache from the indexer for a given namespace and name.
func (s redisGCacheNamespaceLister) Get(name string) (*v1alpha1.RedisGCache, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("redisgcache"), name)
	}
	return obj.(*v1alpha1.RedisGCache), nil
}
